CREATE TABLE mom (
    id            UUID PRIMARY KEY,
    host          VARCHAR(45) NOT NULL UNIQUE,
    port          SMALLINT NOT NULL,
    is_up         BOOLEAN NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    UNIQUE        (host, port)
);
