CREATE TABLE message (
    id            UUID PRIMARY KEY,
    queue_label   VARCHAR(255) NOT NULL,
    topic         VARCHAR(255) NOT NULL,
    expires_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    content       BYTEA NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    CONSTRAINT    fk_queue FOREIGN KEY(queue_label) REFERENCES queue(label) ON DELETE CASCADE
);
